FROM ubuntu:24.10


RUN apt-get update && \
    apt-get install -y sysstat procps fuse libfuse2 ssh openssh-server jsvc libxml2-utils wget zip gzip p7zip bzip2 duperemove borgbackup restic && \
    wget http://www.opendedup.org/downloads/sdfs_3.10.8_amd64.deb && \
    dpkg -i sdfs_3.10.8_amd64.deb

    
COPY monitoramento.sh /usr/src/app/monitoramento.sh
COPY start.sh /usr/src/app/start.sh
RUN chmod +x /usr/src/app/start.sh
RUN chmod +x /usr/src/app/monitoramento.sh

WORKDIR /usr/src/app

CMD ["sh", "/usr/src/app/start.sh"]